# Generated by Django 4.2.7 on 2023-12-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('task', models.TextField(max_length=1000)),
                ('depart', models.CharField(choices=[('Ing', 'Inginerie'), ('HR', 'Human Resource'), ('S', 'Sales'), ('Mng', 'Management')], max_length=3)),
            ],
        ),
    ]
