# Generated by Django 4.2.7 on 2023-12-02 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todotask', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='depart',
            new_name='departament',
        ),
    ]
