# Generated by Django 4.2.7 on 2023-12-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todotask', '0002_rename_depart_todo_departament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='departament',
            field=models.CharField(choices=[('Inginerie', 'Inginerie'), ('HR', 'Human Resource'), ('Sales', 'Sales'), ('Management', 'Management')], max_length=50),
        ),
    ]
