# Generated by Django 4.2.7 on 2023-12-03 10:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todotask', '0003_alter_todo_departament'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Task creation'),
            preserve_default=False,
        ),
    ]
