# Generated by Django 4.2.7 on 2023-12-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todotask', '0004_todo_date_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('WIP', 'WIP'), ('DONE', 'DONE')], default='DONE', max_length=50),
            preserve_default=False,
        ),
    ]
